/*
 Generated by typeshare 1.13.4
*/

/** 创建笔记的输入。 */
export interface CreateNoteDto {
	taskId?: string;
	content: string;
}

/** 分类聚合（独立聚合根）。 */
export interface Category {
	id: string;
	name: string;
	color: string;
	createdAt: string;
}

/** 创建分类的输入。 */
export interface CreateCategoryDto {
	name: string;
	color?: string;
}

/** 更新分类的输入（字段全部可选，但至少提供一个）。 */
export interface UpdateCategoryDto {
	name?: string;
	color?: string;
}

/** 设置任务所属分类的输入（`null` 表示清除归属）。 */
export interface SetTaskCategoryDto {
	categoryId?: string | null;
}

/** 创建任务的输入。 */
export interface CreateTaskDto {
	title: string;
}

/** 原子创建任务并附带首条笔记的输入。 */
export interface CreateTaskWithNoteDto {
	title: string;
	content: string;
}

/**
 * 附属于任务（或独立）的笔记聚合。
 * 
 * `task_id` 为 `None` 时序列化会**省略该字段**（而非输出 `null`），这样与
 * typeshare 生成的 `taskId?: string` 语义一致，前后端共享契约才准确。
 */
export interface Note {
	id: string;
	taskId?: string;
	content: string;
	createdAt: string;
}

/** 待办任务聚合。 */
export interface Task {
	id: string;
	title: string;
	completed: boolean;
	createdAt: string;
	categoryId?: string | null;
}

/** 分页后的任务列表。 */
export interface TaskList {
	items: Task[];
	total: number;
}

/**
 * 任务列表查询条件（全部可选，仅出现的条件参与过滤/排序/分页）。
 * 
 * `limit`/`offset` 用 `i32`：typeshare 不支持 `i64`（JS 无 64 位整数），且分页
 * 参数用 `i32` 足够，JSON 序列化行为与 `i64` 完全一致。
 */
export interface TaskQuery {
	keyword?: string;
	completed?: boolean;
	sort?: string;
	sortDir?: string;
	limit?: number;
	offset?: number;
}

/** 更新笔记的输入。 */
export interface UpdateNoteDto {
	content?: string;
}

/** 更新任务的输入（字段全部可选，但至少提供一个）。 */
export interface UpdateTaskDto {
	title?: string;
	completed?: boolean;
}

