 Generated by specta. Do not edit manually.
// This file has been generated by Specta. Do not edit this file manually.
/**  分类聚合：名称 + 展示色 + 创建时间。 */
export type Category = {
	id: string,
	name: string,
	color: string,
	createdAt: string,
};

/**  创建分类的输入。 */
export type CreateCategoryDto = {
	name: string,
	color: string | null,
};

/**  创建笔记的输入。 */
export type CreateNoteDto = {
	taskId: string | null,
	content: string,
};

/**  创建任务的输入。 */
export type CreateTaskDto = {
	title: string,
};

/**  原子创建任务并附带首条笔记的输入。 */
export type CreateTaskWithNoteDto = {
	title: string,
	content: string,
};

/**
 *  附属于任务（或独立）的笔记聚合。
 * 
 *  `task_id` 为 `None` 时 TypeScript 类型为 `taskId?: string`（可选字段），
 *  前后端共享契约保持一致。
 */
export type Note = {
	id: string,
	taskId: string | null,
	content: string,
	createdAt: string,
};

/**  设置任务所属分类的输入（`null` 表示清除归属）。 */
export type SetTaskCategoryDto = {
	categoryId: string | null,
};

/**  待办任务聚合。 */
export type Task = {
	id: string,
	title: string,
	completed: boolean,
	categoryId: string | null,
	createdAt: string,
};

/**  分页后的任务列表。 */
export type TaskList = {
	items: Task[],
	total: number,
};

/**  任务列表查询条件（全部可选，仅出现的条件参与过滤/排序/分页）。 */
export type TaskQuery = {
	keyword: string | null,
	completed: boolean | null,
	sort: string | null,
	sortDir: string | null,
	limit: number | null,
	offset: number | null,
};

/**  更新分类的输入（字段全部可选，但至少提供一个）。 */
export type UpdateCategoryDto = {
	name: string | null,
	color: string | null,
};

/**  更新笔记的输入。 */
export type UpdateNoteDto = {
	content: string | null,
};

/**  更新任务的输入（字段全部可选，但至少提供一个）。 */
export type UpdateTaskDto = {
	title: string | null,
	completed: boolean | null,
};
