//! 使用 specta 将 Rust 类型导出为 TypeScript。
//!
//! 在 `main.rs` 中通过 `--export-types` 标志触发，生成
//! 前端 `src/domain/generated.ts` 文件。

use specta::Types;
use specta_serde::Format;
use specta_typescript::Typescript;

use crate::domain::task::Task;
use crate::domain::note::Note;
use crate::domain::category::Category;
use crate::domain::repository::TaskQuery;
use crate::domain::repository::TaskList;
use crate::application::dto::{
    CreateTaskDto, CreateTaskWithNoteDto, UpdateTaskDto, CreateNoteDto,
    UpdateNoteDto, CreateCategoryDto, UpdateCategoryDto, SetTaskCategoryDto,
};

/// 导出所有带 `#[derive(Type)]` 的类型为 TypeScript 文件。
pub fn export_types() -> Result<(), Box<dyn std::error::Error>> {
    let mut types = Types::default();
    types = types.register::<Task>();
    types = types.register::<Note>();
    types = types.register::<Category>();
    types = types.register::<TaskQuery>();
    types = types.register::<TaskList>();
    types = types.register::<CreateTaskDto>();
    types = types.register::<CreateTaskWithNoteDto>();
    types = types.register::<UpdateTaskDto>();
    types = types.register::<CreateNoteDto>();
    types = types.register::<UpdateNoteDto>();
    types = types.register::<CreateCategoryDto>();
    types = types.register::<UpdateCategoryDto>();
    types = types.register::<SetTaskCategoryDto>();

    Typescript::default()
        .header(" Generated by specta. Do not edit manually.")
        .export_to("src/domain/generated.ts", &types, Format)
        .expect("导出 TypeScript 类型失败");
    Ok(())
}
